### ISSUE TITLE
Can you replace the T265 with a realsense d435i?

### ISSUE THREAD

**Issue by Bailey-24** [RealRobotSquad/FastUMI_Data#1]

**Comment by Bailey-24** [comment]
就是用T265，那T265本来就可以获取鱼眼图片和机器臂末端轨迹信息，为什么还需要go pro。
就是硬件能否再简化或者通用一点点，考虑一些穷实验室是没有那么多资源买这么多设备的
https://blog.csdn.net/u013595260/article/details/108470791

**Comment by zxzm-zak** [comment]
Thank you for your question. The binocular fisheye camera of the T265 captures grayscale images without RGB images. When we tested the ACT and DP models, we found that the lack of RGB information has a certain impact on model inference. In addition, we also tested the D435i. Since the field of view of the D435i is very narrow, when used as a first-person perspective, its image becomes completely blocked when approaching objects, making accurate inference impossible.
During our tests, we found that for ACT and DP, a fisheye camera with nearly a 180-degree field of view can replace the combined inference of a D435i from both first-person and third-person perspectives. In addition, the anti-shake of Go Pro helps to stabilize the picture, although we did not conduct a detailed comparison in this aspect. 
If you want to try it, I think you can try using images from the T265 camera for training and inference. It may perform better than us on your model.

**Comment by lunalulu** [comment]
@Bailey-24 请问你有尝试使用t265的灰度图像进行训练和推理吗，效果怎么样？我这边训练了几个任务都不太行呢

**Comment by Bailey-24** [comment]
官方说会release改进的算法，你是用什么算法

**Comment by lunalulu** [comment]
> 官方说会release改进的算法，你是用什么算法

我用的就是umi的dp算法，你有训练吗？有测试效果吗？
